### PR TITLE
Add v86 example, currently not working

### PR DESCRIPTION
**Pull request by jackrusher**
This adds a `browser` subdirectory with everything needed to boot an emulated Pentium with SeaBIOS and a VGA BIOS that tries to load a bootable hard drive image from the file `code.img` in the same directory. My attempts to actually run a Mu image currently fail with some bad VGA memory and an exception visible in the console. Hopefully you'll be able to debug whatever incompatibility might exist between Mu and this emulator.

### CODE REVIEW

**Comment by akkartik** [comment]
Jack and I spent several weeks around the time this ticket was created, trying to get Mu working on https://github.com/copy/v86, but quite without success. I also saw signs that Mu is quite slow on v86 except on Chrome on some platforms. (I wasn't able to characterize precisely what platforms. Mac OS of some varieties.) Many thanks, Jack. Hopefully I'll work on this again sometime.

**Comment by copy** [comment]
There is a bug in v86 related to the interrupt mask in the pic. I'll push a fix soon.

**Comment by copy** [comment]
This has been fixed in v86. I've added a profile here: https://copy.sh/v86/?profile=mu

You can download it from here: https://github.com/copy/v86/releases

Note that to get it to work, you need the v86.wasm file. I also had to raise the memory size to 128m.

**Comment by akkartik** [comment]
Thanks so much!! I just noticed it on [the Advent of v86](https://copy.sh/v86/advent/2023/?day=4) calendar.

**Pull request closed without merging**
